### ISSUE TITLE
error

### ISSUE THREAD

**Issue by WoodyBryant** [yxfish13/PostgreSQL12.1_hint#1]
When executing command "make" in the stage of "Install pg_hint_plan", I got an error "pg_hint_plan.c:16:10: fatal error: access/relation.h: No such file or directory", I meet difficulties here. Can anybody help me solve it?

**Comment by yxfish13** [comment]
Check the following:
1. Check whether the PostgreSQL 12 version is used. Different PG versions have different hint plug-in requirements.
2. Do you use the source code to install pg12? If not, you may need to install the dev plug-in to use the pg plug-in.

**Comment by WoodyBryant** [comment]
> 2\.

Thank you, but I have solved the problems. The reason is not two of the above. Instead, the PG_CONFIG in the Makefile should be changed according to the path installing the PG. Anyway, thanks for your consideration.
